[mypy]
namespace_packages = True
disallow_incomplete_defs = True
disallow_untyped_calls = True
disallow_untyped_defs = True
warn_unused_configs = True
check_untyped_defs = True
disallow_untyped_decorators = True
no_implicit_optional = True
warn_redundant_casts = True
warn_unused_ignores = True
warn_return_any = True
strict_equality = True
disallow_any_generics = True
disallow_subclassing_any = True

[mypy-tests.*]
disallow_untyped_defs = False

# Internal packages that ought to have type information

[mypy-ontology.*]
ignore_missing_imports = True

[mypy-vdf_lib.*]
ignore_missing_imports = True

[mypy-morphun.*]
ignore_missing_imports = True

[mypy-nludf.*]
ignore_missing_imports = True

[mypy-nlxbundles.*]
ignore_missing_imports = True

[mypy-marrs.*]
ignore_missing_imports = True

[mypy-turibolt.*]
ignore_missing_imports = True

[mypy-turihub.*]
ignore_missing_imports = True

[mypy-vocparser.*]
ignore_missing_imports = True

[mypy-turibolt_py_blobby_client.blobby_client.*]
ignore_missing_imports = True

[mypy-nlxsplunker.*]
ignore_missing_imports = True

[mypy-CDMTokenizer.*]
ignore_missing_imports = True

# External packages

[mypy-genson.*]
ignore_missing_imports = True

[mypy-jsonschema.*]
ignore_missing_imports = True

[mypy-yamlinclude.*]
ignore_missing_imports = True

[mypy-pyarrow.*]
ignore_missing_imports = True

[mypy-scipy.stats.*]
ignore_missing_imports = True

[mypy-tqdm.*]
ignore_missing_imports = True

[mypy-ruamel.*]
ignore_missing_imports = True

[mypy-google.cloud.*]
ignore_missing_imports = True

[mypy-joblib.*]
ignore_missing_imports = True

[mypy-retrying.*]
ignore_missing_imports = True

[mypy-dns_cache.*]
ignore_missing_imports = True

[mypy-joblib_zstd.*]
ignore_missing_imports = True

[mypy-toolz.*]
ignore_missing_imports = True

[mypy-guppy.*]
ignore_missing_imports = True

[mypy-fastjsonschema.*]
ignore_missing_imports = True

[mypy-ray.*]
follow_imports = skip

[mypy-purl.*]
ignore_missing_imports = True
