[project]
name = "restaurant-agent"
version = "0.1.0"
description = "Agent that recommend restaurants in Barcelona."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cohere>=5.15.0",
    "fastapi>=0.115.12",
    "googlemaps>=4.10.0",
    "httpx>=0.28.1",
    "llama-index==0.12.50",
    "llama-index-callbacks-opik>=1.1.0",
    "llama-index-embeddings-google-genai>=0.1.0",
    "llama-index-llms-groq>=0.3.1",
    "llama-index-utils-workflow>=0.3.1",
    "loguru>=0.7.3",
    "numpy==1.26",
    "opik>=1.7.11",
    "polars>=1.30.0",
    "psycopg2==2.9.10",
    "psycopg>=3.2.9",
    "pydantic-settings>=2.8.1",
    "uvicorn>=0.34.2",
    "time-uuid>=0.2.0",
    "vecs>=0.4.5",
    "llama-index-vector-stores-postgres>=0.5.4",
    "crawl4ai>=0.6.3",
    "pytest>=8.3.5",
    "asyncpg>=0.30.0",
]

