start-qdrant:
	docker-compose -f docker-compose-qdrant.yaml up -d

start-pgvector:
	docker-compose -f docker-compose-pgvector.yaml up -d


stop-pgvector:
	docker-compose -f docker-compose-pgvector.yaml down