[project]
name = "load-places"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastexcel>=0.14.0",
    "googlemaps>=4.10.0",
    "loguru>=0.7.3",
    "polars>=1.29.0",
    "pydantic-settings>=2.9.1",
    "xlsxwriter>=3.2.3",
]
